# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'


target 'Neshan' do
  use_frameworks!
  
  pod 'FAlamofire', :path => '../FAlamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NeshanMobileSDK', '~> 0.9.5'
  pod 'FittedSheets'
  pod 'IQKeyboardManagerSwift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
 	target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            config.build_settings['SWIFT_VERSION'] = '5.0'
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
            config.build_settings["CODE_SIGNING_ALLOWED"] = 'NO'
      end
  end
end
